name: manydepth
channels:
  - default
  - pytorch
  - conda-forge
dependencies:
  - python 3.8
  - opencv=4.5
  - matplotlib=3.1.2
  - numpy=1.19.5
  - pip
  - pip:
    - Pillow
    - tensorboardX==2.6.2
    - scikit-image==0.16.2
    - torch==2.4.1
    - torchvision==0.15.1
    - tqdm==4.57.0
